---
stores:
  yaml:
    indent: 2

creation_rules:
  - path_regex: charts/tailscale-operator/values.sops.yaml$
    encrypted_regex: "^(oauth)$"
    age:
      - age1vqqd3t7f5ga8fjue9w27alqw7utnm7wdaze627y4udl3ntsgt37sz8h4rz
