---
apiVersion: v2
name: dns-config
description: DNS configuration
type: application
version: 0.1.0
dependencies:
  - name: external-dns
    version: 1.19.x
    repository: https://kubernetes-sigs.github.io/external-dns
