---
defaults:
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"

ingress:
  - namespace: argocd
    host: argocd.hugoplanet.se
    service:
      name: argo-cd-argocd-server
      port: 80
