---
apiVersion: v2
name: kube-prometheus-stack
description: Prometheus stack
type: application
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: 79.7.x
    repository: https://prometheus-community.github.io/helm-charts
